Repository nicocadq/final-progII, pull requests merged in 2020-11, with the labels that each got.

#26 Added some methods to controlle db
  final-progII/src/logic/Absence.java
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/Exam.java
  final-progII/src/logic/Functionary.java
  final-progII/src/logic/Student.java
  final-progII/src/logic/Subject.java
  final-progII/src/logic/Teacher.java
  final-progII/src/logic/User.java
  final-progII/src/persistence/ControllerDB.java
Labels: to test

#27 Implemented some methods on ControllerLogic
  SCRIPT.sql
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/main.java
  final-progII/src/persistence/ControllerDB.java
Labels: to test, wip

#21 Added UI for create user
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/main.java
  final-progII/src/presentation/Menu.java
  final-progII/src/presentation/Screen.java
Labels: enhancement

#29 UI login
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/presentation/Screen.java
Labels: to test

#49 Implemeted UI to list subjects
  final-progII/src/presentation/Screen.java
Labels: enhancement

#48 Implemented consult user but without the enrolled box
  final-progII/src/presentation/Screen.java
Labels: enhancement

#51 feature/consult absence
  final-progII/src/logic/main.java
  final-progII/src/presentation/Screen.java
Labels: enhancement

#50 Implemented UI to create absences
  final-progII/src/presentation/Screen.java
Labels: enhancement

#53 feature/create-exam
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/main.java
  final-progII/src/presentation/Screen.java
Labels: enhancement

#68 List pendings
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/main.java
  final-progII/src/persistence/ControllerDB.java
  final-progII/src/presentation/Menu.java
  final-progII/src/presentation/Screen.java
Labels: wip

#71 Add some functiolaties in List Pendings, without logic
  final-progII/src/logic/ControllerLogic.java
  final-progII/src/logic/main.java
  final-progII/src/persistence/ControllerDB.java
  final-progII/src/presentation/Menu.java
  final-progII/src/presentation/Screen.java
Labels: bug, wip

#78 Implement subject update on UI
  final-progII/src/presentation/Screen.java
Labels: enhancement
